#!/bin/bash

echo "🔧 Debug Específico de isAuthenticated"
echo "======================================"

echo ""
echo "📝 Passos para debugar:"
echo "1. Acesse: http://localhost:9011"
echo "2. Abra DevTools (F12) → Console"
echo "3. Tente fazer login com CPF: 398.780.438-60 e senha: 123456"
echo ""
echo "🔍 Logs importantes para observar:"
echo "   ✅ 'Tentando autenticar com: ...'"
echo "   ✅ 'Cliente encontrado: ...'"
echo "   ✅ 'Cookies salvos: ...'"
echo "   ⚠️  'isAuthenticated - debug: ...' (novo log adicionado)"
echo "   ⚠️  'Router Debug: ...' (verifique se isAuthenticated é true)"
echo ""
echo "🎯 O que deve acontecer:"
echo "   1. Login encontra o cliente"
echo "   2. Salva cookies com expires_at"
echo "   3. isAuthenticated() verifica se token não expirou"
echo "   4. Router permite acesso a /system/"
echo ""
echo "🚨 Se isAuthenticated ainda for false:"
echo "   - Verifique se expires_at está no futuro"
echo "   - Verifique se o formato da data está correto"
echo "   - Observe os logs de 'isAuthenticated - debug'"